### PR TITLE
Add KHR_materials_emissive_strength extension

### LINKED ISSUE #367: Add emissive KHR_material_emissive_strength extension
I need it for a project, it would be nice

### PR DESCRIPTION
**Pull request by stefnotch**
Add https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_emissive_strength/README.md
Fix #367

### CODE REVIEW

**Comment by JMS55** [comment]
@alteous is there any chance we could get this reviewed/merged? Blender uses this extension any time you export emissive meshes, and is needed for Bevy to properly load them.

**Comment by schell** [comment]
When is the next planned release? I would love to integrate this into [renderling](https://github.com/schell/renderling).

**Comment by alteous** [comment]
I'll aim to get a new release out by the end of next week.

**Comment by JMS55** [comment]
@alteous polite reminder to please release a new version on crates.io :). Looking forward to integrating this into bevy!

**Pull request merged**
