### PR TITLE
Add slice import for web targets

### PR DESCRIPTION
**Pull request by ForsakenHarmony**
will crash in wasm on gltf files with external blobs, but that's to be expected

### CODE REVIEW

**Comment by alteous** [comment]
Thanks for your pull request.

Unfortunately, I'm unwilling to merge as-is. What bothers me is this line:
```rust
import_impl(Gltf::from_slice(slice)?, Path::new("./"))`
```
What this does it assumes any relative URIs are relative to the current working directory, which I think is unreasonable.

**Comment by ForsakenHarmony** [comment]
The point is that there is no file system on the web, implementing async loading of other files would be a huge undertaking

**Comment by ForsakenHarmony** [comment]
OK?

**Comment by ForsakenHarmony** [comment]
I guess you're just never gonna explain why you just closed this?

**Comment by ForsakenHarmony** [comment]
Or is this possible with `Gltf::from_slice`

**Comment by ForsakenHarmony** [comment]
Nope

**Pull request closed without merging**
