### PR TITLE
Propagate detailed error information in Display impl

### PR DESCRIPTION
**Pull request by Ralith**
This would have made my debugging of #181 (and a few other issues) go much smoother.

### CODE REVIEW

**Comment by alteous** [comment]
I don't understand the issue here. Could you detail exactly why "JSON error" was reported on the duck model (I suspect the validation steps failed) and whether `println!("{:?}", error)` was more detailed?

**Comment by alteous** [comment]
I'm unable to reproduce the issue described in #181 because the code has been fixed since. :)

**Comment by Ralith** [comment]
The really important change here is just forwarding to the wrapped errors' `Display` impls instead of ignoring them.

**Comment by alteous** [comment]
Seems reasonable to me. Thanks. :)

**Pull request merged**
