### PR TITLE
Do not serialize None

### PR DESCRIPTION
**Pull request by wlinna**
Fixes https://github.com/gltf-rs/gltf/issues/173

After these changes (and the now already merged padding fix) I'm able to open serialized binary glTF files in ThreeJS.

Similarly, all empty vectors **must** be left unserialized, but this PR is about `None`s

### CODE REVIEW

**Comment by wlinna** [comment]
I noticed a problem with this PR. Fix incoming.

**Comment by wlinna** [comment]
I've fixed the problem now

**Comment by alteous** [comment]
I wonder whether there's a less human-error-prone way of doing this, perhaps with a new type?

```rust
#[derive(Deserialize)]
struct VecDeserializeOnly<T>(pub Vec<T>);

impl Serialize for VecDeserializeOnly {
    fn serialize() {
        // nop
    }
}
```

**Comment by wlinna** [comment]
Is your comment by any chance related to [the other PR](https://github.com/gltf-rs/gltf/pull/177)? Or maybe I'm just missing your idea.

Also, why would you turn of serialize?

**Comment by alteous** [comment]
They're very similar cases: the idea is to create a new type whose `Serialize` implementation is specialised in a single place instead of everywhere it is used. The psuedo-code example was intended to demonstrate this idea.

**Comment by alteous** [comment]
Instead of applying `serde(skip_serializing_if)` we `impl Serialize for Extras` such that it is not serialized anywhere.

**Comment by wlinna** [comment]
But my use case **requires** extras. The support for deserializing and serializing `extras` was the entire reason why I picked this library. I used this library for a small utility to write certain metadata to my GLB files.

**Comment by alteous** [comment]
> such that it is not serialized anywhere.

Correction: I mean to say "such that it is serialized as needed", implying the suggested alternative would achieve the same results as the changes in this PR, except the implementation being in one place. Does that make sense? I'll demonstrate with a PR this evening.

**Comment by wlinna** [comment]
Yeah, I think we are on the same page now. I'll be glad to see that PR, as I'm very new to programming in Rust (except that I've read This Week in Rust since its inceptions).

**Comment by alteous** [comment]
After some experimenting I realise my suggestion is not better in any way. Let's go with the simpler option as you have already implemented. Thanks for the PRs, as always! :)

Are there likely to be further changes/PRs in the next couple of days? If so I'd rather wait for them before publishing since since publishing is time consuming.

**Comment by wlinna** [comment]
I'm not going to make any PRs unless I notice something new, which is unlikely, given that the library already works well for my use case.

You're welcome :)

**Comment by alteous** [comment]
I wonder whether we need to address `HashMap` too.

**Comment by alteous** [comment]
Hmm... `attributes` is a required field so the deserialization should fail. If the user happens to remove all the attributes and attempts to serialize then perhaps the serializer should fail.

**Pull request merged**
