### PR TITLE
Use nalgebra instead of cgmath

### LINKED ISSUE #197: Replace cgmath by nalgebra through feature flags
Hello,

From what I gathered, gltf uses cgmath for pure operations over Vectors/Matrices/Quaternions (in scene::Transform);
It'd be nice to have an optional dependency on cgmath for those who are using nalgebra in their projects instead
I can try starting a PR if this is something you'd be willing to merge

Thanks

### PR DESCRIPTION
**Pull request by alteous**
Closes #197

### CODE REVIEW

**Comment by aloucks** [comment]
Is this really that beneficial? nalgebra takes 28 seconds to build on my machine. cgmath takes 5 seconds.

**Comment by alteous** [comment]
It seems `cgmath` is no longer actively maintained and people are switching to `nalgebra` instead. If people are already using `nalgebra` in their projects then I imagine there will be no increase in build time.

**Comment by aloucks** [comment]
Not everyone is switching to nalgebra right now and it's a big dependency for a handful of transformation functions. Would you be open to having a `math` module in gltf-rs that adds the transformation functions from cgmath or nalgebra (and dropping both dependencies)?

**Comment by alteous** [comment]
#223 implements what you describe. The code was taken from `cgmath` so there is a licensing concern: can we sub-licence as MIT?

**Comment by alteous** [comment]
Web search reveals Apache is not a copyleft licence, which means derivative works or modified versions are not required to be released under the same licence. The restriction is that the original licence must be retained and identified as having been modified. Therefore #223 should be a solution.

**Comment by alteous** [comment]
Closed in favour of #223.

**Pull request closed without merging**
